### ISSUE TITLE
Official release of 2.0?

### ISSUE THREAD

**Issue by Webonaute** [phpDocumentor/ReflectionCommon#20]
seem to make a year its beta and no new commit. can it be marked stable?

**Comment by jaapio** [comment]
No it can't. Work is still in progress.

**Comment by jaapio** [comment]
Excuse me, I missed the actual repository. 

I think this library can be released very soon.

**Comment by jaapio** [comment]
https://github.com/phpDocumentor/ReflectionCommon/releases/tag/2.0.0 

Here you go.

**Comment by Webonaute** [comment]
great!
