### ISSUE TITLE
FQSEN constructor does not accept all valid PHP Class Names

### ISSUE THREAD

**Issue by nicmart** [phpDocumentor/ReflectionCommon#7]
FQSEN constructor accepts only alphanumeric characters, but a lot more are allowed in PHP.
This makes parsing in ReflectionDocBlock fail with valid php class names.

From [PHP Documentation](http://php.net/manual/en/language.oop5.basic.php):

> A valid class name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: ^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$.

For example `Option«T»` is a valid Interface Name, but is not a valid FQSEN name.

In a library I am working on I need to handle this special chars, and to do so I committed a small patch to the regexp in a fork: https://github.com/nicmart/ReflectionCommon/commit/9f3d9ea46181a75d03bfbbc9f72b281daa9dccc1

If you agree that this is an issue that has to be fixed, I can open a pull request with the fix.

Thanks!

**Comment by nicmart** [comment]
Any update on this? Is the repo still maintained?

**Comment by jaapio** [comment]
Hi @nicmart,

Think you are right about this. I would be happy to accept your PR on this.

**Comment by jaapio** [comment]
Hi @nicmart,

I found some time to fix this. It would be very nice if you could do a review.

Thanks!
